"""
System Ver19 - MACD Divergence Strategy 設定ファイル
Ver19: 5分足RCI±70反転 + 5M PO + 暫定ピボットDiv
       ※1H PO条件なし、1H RCI条件なし（Divのみ）
"""

from pathlib import Path
_PROJECT_ROOT = Path(__file__).parent.parent.parent
DATA_DIR = str(_PROJECT_ROOT / "ローソク足データ")
DATA_5M = f"{DATA_DIR}/GBPJPY_5M_2015-2025.csv"
DATA_1H = f"{DATA_DIR}/GBPJPY_1H_2013-2025.csv"
DATA_4H = f"{DATA_DIR}/GBPJPY_4H_2013-2025.csv"

SYMBOL = "GBPJPY"
INITIAL_CAPITAL_USD = 10000
INITIAL_CAPITAL_JPY = 1500000
POSITION_SIZE = 10000
LOT_SIZE = 0.1

TRADING_START_HOUR = 8
TRADING_END_HOUR = 24

# RCI設定
RCI_SHORT = 9
RCI_5M_THRESHOLD = 70  # 5分足: ±70到達後、反転

# Ver19: 1H RCI条件なし
USE_1H_RCI = False
RCI_1H_THRESHOLD = 60

# EMA (1時間足パーフェクトオーダー用)
USE_1H_PO = False  # Ver19: 1H POなし
EMA_1H_SHORT = 20
EMA_1H_MID = 30
EMA_1H_LONG = 40

# EMA (5分足パーフェクトオーダー用)
EMA_5M_SHORT = 20
EMA_5M_MID = 30
EMA_5M_LONG = 40

# MACD
MACD_FAST = 6
MACD_SLOW = 13
MACD_SIGNAL = 4

# ZigZag
ZIGZAG_1H_DEPTH = 12
ZIGZAG_1H_DEVIATION = 5
ZIGZAG_1H_BACKSTEP = 3
ZIGZAG_5M_DEPTH = 5
ZIGZAG_5M_DEVIATION = 3
ZIGZAG_5M_BACKSTEP = 2

# ダイバージェンス設定
DIVERGENCE_VALID_HOURS = 12
USE_PROSPECTIVE_PIVOT = True
USE_HIDDEN_DIVERGENCE = True
USE_REGULAR_DIVERGENCE = True

# リスク管理
RISK_REWARD_RATIO = 1.5
ENABLE_1DIV1ENTRY = True
SL_BUFFER_PIPS = 2
SL_ATR_LENGTH = 14
SL_ATR_MULT = 1.0
SL_FALLBACK_ATR_MULT = 2.0
SL_MIN_ATR_MULT = 0.5
SPREAD_PIPS = 0.5

# バックテスト期間
BACKTEST_START = "2015-11-15"
BACKTEST_END = "2025-11-24"

# 出力設定
RESULTS_DIR = "./scripts/results_v19"
REPORT_FILE = f"{RESULTS_DIR}/backtest_report_v19.txt"
TRADES_CSV = f"{RESULTS_DIR}/trades_v19.csv"
DIVERGENCES_CSV = f"{RESULTS_DIR}/divergences_v19.csv"

POINT_VALUE = 0.01
